version: '3.8'

services:
  mysql-db:
    image: mysql
    restart: always
    environment:
      - "MYSQL_DATABASE=bd_inventario"
      - "MYSQL_USER=panther"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3307:3306"

  springboot:
    build: .
    restart: always
    ports:
      - "8090:8080"
    environment:
      - "spring_profiles_active=prod"
      - "MYSQL_URL=jdbc:mysql://mysql-db:3306/bd_inventario?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      - "MYSQL_USERNAME=panther"
      - "MYSQL_PASSWORD=1234"
    depends_on:
      - mysql-db
