spring:
  datasource:
    url: jdbc:mysql://root:IbooPacZ9JqnE1JgQ0zs@containers-us-west-51.railway.app:6674/railway
    username: root
    password: IbooPacZ9JqnE1JgQ0zs
    name: productos-api

  sql:
    init:
      mode: always